"""add a subscribers model.

Revision ID: 29869a2f6ec1
Revises: 8b6ae8ccf09f
Create Date: 2022-05-17 21:23:21.636303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29869a2f6ec1'
down_revision = '8b6ae8ccf09f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscribers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscribers_email'), 'subscribers', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subscribers_email'), table_name='subscribers')
    op.drop_table('subscribers')
    # ### end Alembic commands ###
